---
title: "Performance of dual and triple fungicide premixes for the control of soybean target spot after seven years"
author: Evandro Puhl de Melo | Ricardo Gomes Tomáz | Cláudia Vieira Godoy | Emerson Medeiros Del Ponte.
format: 
  html:
    code-fold: false
    smooth-scroll: true
    fig-width: 16
    fig-height: 10
    css: styles.css
    self-contained: true
    #code-tools:
      #source: true
      #toggle: true
      #caption: "Source code"
theme: "cosmo"
toc: true
toc-location: right
toc-depth: 10
fontcolor: "black" # {html} Color of text.
linkcolor: "#007FFF" # {html, pdf, beamer} Color of link text.
reference-location: "margin"
colortheme: "black"
highlight: monochrome
warning: false
cache: true
---

# Packages

```{r}
library(tidyverse)
library(gsheet)
library(broom)
library(metafor)
library(dplyr)
library(ggthemes)
library(plyr)
library(janitor)
library(metafor)
library(cowplot)
```

```{r}
ma <- gsheet2tbl("https://docs.google.com/spreadsheets/d/151DE26uSMN4WBS0PTQcjdw7BO56gXy_VilFZS3b9AAM/edit?usp=sharing")
head(ma)
```

# Descriptive

## Yield

```{r}
yield = ma %>% 
  filter(ai %in% c("BIX+PROT+TRIFL", "_CHECK", "FLUX+PYRA")) %>% 
  ggplot(aes(yld))+
  geom_histogram(color = "white", fill = "darkred")+
  facet_wrap(~ai)+
  theme_few()+
  labs(x = "Yield (kg/ha)",
       y = "Frequency")+
  theme(text = element_text(face = "bold",size = 14))

ggsave("fig/yield.png", bg = "white", width = 10, height = 8)
  
```

## Yield x Year

```{r}
yield_year = ma %>% 
  filter(ai %in% c("BIX+PROT+TRIFL", "_CHECK", "FLUX+PYRA")) %>% 
  ggplot(aes(as.factor(year),yld))+
  #geom_histogram(color = "white", fill = "darkgreen")+
  geom_boxplot(fill = NA, color = "black", size = 1)+
  facet_wrap(~ai)+
  theme_few()+
  labs(x = "Year",
       y = "Yield (kg/ha)")+
  #coord_flip()+
  theme(text = element_text(face = "bold",size = 14),
        strip.text = element_blank())

ggsave("fig/yield_year.png", bg = "white", width = 10, height = 8)
```

### Plot

```{r}
plot_grid(yield,yield_year, labels = c("AUTO"), ncol = 1)
ggsave("fig/frequency_boxplot_yield.png", bg = "white", height = 8, width = 10)
```

## Severity

```{r}
severity = ma %>% 
  filter(ai %in% c("BIX+PROT+TRIFL", "_CHECK", "FLUX+PYRA")) %>% 
  ggplot(aes(sev))+
  geom_histogram(color = "white", fill = "darkgreen")+
  facet_wrap(~ai)+
  theme_few()+
  labs(x = "Severity (%)",
       y = "Frequency")+
  theme(text = element_text(face = "bold",size = 14))

ggsave("fig/severity.png", bg = "white", width = 10, height = 8)
```

## Severity x Year

```{r}
severity_year = ma %>% 
  filter(ai %in% c("BIX+PROT+TRIFL", "_CHECK", "FLUX+PYRA")) %>% 
  ggplot(aes(as.factor(year),sev))+
  #geom_histogram(color = "white", fill = "darkgreen")+
  geom_boxplot(fill = NA, color = "black", size = 1)+
  facet_wrap(~ai)+
  theme_few()+
  labs(x = "Year",
       y = "Severity (%)")+
  #coord_flip()+
  theme(text = element_text(face = "bold",size = 14),
        strip.text = element_blank())

ggsave("fig/severity_year.png", bg = "white", width = 10, height = 8)
```

### Plot

```{r}
plot_grid(severity,severity_year, labels = c("AUTO"), ncol = 1)
ggsave("fig/frequency_boxplot_severity.png", 
       bg = "white", height = 8,width = 10)
```

# Meta-analysis

## Severity and yield

```{r}
ma

ma1 <- ma %>% 
  #filter(ai %in% c("BIX+PROT+TRIFL", "_CHECK", "FLUX+PYRA")) %>%
  dplyr::group_by(study, year, location, state, ai) %>% 
  dplyr::summarise(mean_sev = mean(sev),
            mean_yld = mean(yld))
```

## Severity regression

```{r}
ma_sev <- ma %>% 
  dplyr::filter(!is.na(sev)) %>% 
  dplyr::filter(!is.na(yld)) %>%
  dplyr::filter(yld>0) %>%
  dplyr::group_by(study, year) %>%  
  dplyr::select(ai, block, sev) %>%
  dplyr::group_by(study, year) %>% 
  do(tidy(aov(.$sev ~ .$ai + factor(.$block)))) %>% 
  dplyr::filter(term == "Residuals") %>% 
  dplyr::select(1,2,6) %>% 
  set_names(c("study", "year", "v_sev"))
```

## Yield regression

```{r}
ma_yld <- ma %>% 
  dplyr::filter(!is.na(sev)) %>% 
  dplyr::filter(!is.na(yld)) %>%
  dplyr::filter(yld>0) %>% 
  dplyr::group_by(study, year) %>% 
  dplyr::select(ai, block, yld) %>% 
  dplyr::group_by(study, year) %>% 
  do(tidy(aov(.$yld ~ .$ai + factor(.$block)))) %>% 
  dplyr::filter(term == "Residuals") %>% 
  dplyr::select(1,2,6) %>% 
  set_names(c("study", "year", "v_yld"))
```

### Joining

```{r}
qmr = left_join(ma_sev, ma_yld)
ma_trial = dplyr::full_join(ma1, qmr)

```

### A.I. selection

```{r}
ma3 = ma_trial %>% 
  filter(!is.na(mean_sev)) %>% 
  filter(!is.na(mean_yld)) %>% 
  filter(!is.na(v_sev)) %>% 
  filter(!is.na(v_yld)) %>% 
  filter(ai %in% c("BIX+PROT+TRIFL", "_CHECK", "FLUX+PYRA"))

summary(ma3)


```

### Rename

```{r}
ma3$ai <- revalue(ma3$ai, c("_CHECK" = "AACHECK"))
ma3$ai <- revalue(ma3$ai, c("BIX+PROT+TRIFL" = "BIX + PROT + TRIFL"))
ma3$ai <- revalue(ma3$ai, c("FLUX+PYRA" = "FLUX + PYRA"))

ma3$study = as.factor(ma3$study)
unique(ma3$study)
```

```{r}
#ma3_unique <- ma3 %>%
 # dplyr::distinct(study, .keep_all = TRUE)

ma3 = ma3 %>% # REVISAR
 dplyr::group_by(ai,study,year) %>% 
  dplyr::summarise(
    mean_yld = mean(mean_yld),
    v_yld = mean(v_yld),
    mean_sev = mean(mean_sev),
    v_sev = mean(v_sev)
  )

ma_check = ma3 %>% 
  ungroup() %>% 
  dplyr::filter(ai == "AACHECK")%>% 
  group_by(study) %>% 
  dplyr::mutate(check = ai, sev_check = mean_sev,
                v_sev_check = v_sev, yld_check = mean_yld, v_yld_check = v_yld ) %>% 
 dplyr::select(study, yld_check, v_yld_check, sev_check, v_sev_check)

ma_check = ma_check %>% 
  filter(!is.na(yld_check)) %>% 
  filter(!is.na(v_yld_check)) %>% 
  filter(!is.na(sev_check)) %>% 
  filter(!is.na(v_sev_check))


ma_check = ma_check %>% # REVISAR
 dplyr::group_by(study) %>% 
  dplyr::summarise(
    yld_check = mean(yld_check),
    v_yld_check = mean(v_yld_check),
    sev_check = mean(sev_check),
    v_sev_check = mean(v_sev_check)
  )

ma_data = ma3 %>% 
  full_join(ma_check)

```

## Severity

```{r}
ma_sev <- ma_data %>% 
  filter(mean_sev != "NA") %>% 
  filter(mean_sev>0)

hist(ma_sev$mean_sev)
```

```{r}
ma_sev <- ma_sev %>%
  mutate(log_sev = log(mean_sev))
hist(ma_sev$log_sev)
```

```{r}
ma_sev$vi_sev <- with(ma_sev, v_sev / (4 * mean_sev^2))

summary(ma_sev$vi_sev)

ma_sev = ma_sev %>% 
  filter(!is.na(mean_yld))
```

```{r}
ma_sev <- ma_sev %>%
  filter(!is.na(mean_yld)) %>%
  filter(!is.na(mean_sev)) %>% 
  group_by(study) %>% 
  dplyr::mutate(n2 = n()) %>% 
  filter(n2 != 1)

unique(ma_sev$n2)

summary(ma_sev)
```

## Model fitting

### Overall

```{r}

# Overall

mv_sev <- rma.mv(log_sev, vi_sev,
  mods = ~ai,
  random = list(~ai | factor(study)),
  struct = "HCS",
  method = "ML",
  #control = list(optimizer = "nlm"),
  data = ma_sev)


summary(mv_sev)
#anova(mv_sev, btt = 5:6) 

```

```{r}
mv_sev_means <- emmprep(mv_sev)
library(emmeans)

mv_sev_emmeans <- emmeans(mv_sev_means, ~ ai)
pwpm(mv_sev_emmeans)

emmeans_summary <- summary(mv_sev_emmeans)
emmeans_df <- as.data.frame(emmeans_summary)
colnames(emmeans_df) <- c("ai", "emmeans", "SE", "df", "lower.CL", "upper.CL")

emmeans_df$emmeans = exp(emmeans_df$emmeans)
emmeans_df$SE = exp(emmeans_df$SE)
emmeans_df$lower.CL = exp(emmeans_df$lower.CL)
emmeans_df$upper.CL = exp(emmeans_df$upper.CL)

library(multcomp)
cld(mv_sev_emmeans)
```

##### Estimated

```{r}
efficacy_sev <- data.frame(cbind(
  (1 - exp(mv_sev$b)) * 100,
  (1 - exp(mv_sev$ci.lb)) * 100,
  (1 - exp(mv_sev$ci.ub)) * 100
))

efficacy_sev
```

### Year

```{r}
# Year

mv_sev_year <- rma.mv(log_sev, vi_sev,
  mods = ~ai*year,
  random = list(~ai | factor(study)),
  struct = "HCS",
  method = "ML",
  #verbose = TRUE,
  #control=list(optimizer="Nelder-Mead"),
  data = ma_sev%>% mutate(year= year - 2017))

mv_sev_year

anova(mv_sev_year, btt = 5:6)  
anova(mv_sev_year,mv_sev)
```

#### Declining

```{r}
FLUX_PYRA_dc = (1-exp(0.0576))*100
BIX_PROT_TRIFL_dc = (1-exp(0.0175))*100
```

##### Estimated

```{r}
reg1 = data.frame(mv_sev_year$beta, mv_sev_year$ci.lb, mv_sev_year$ci.ub) %>%
  rownames_to_column("trat") %>%
  tidyr::separate(trat, into = c("lado1", "lado2"), sep = ":") %>%
  tidyr::separate(lado1, into = c("lixo", "lado3"),sep = "ai") %>%
  dplyr::select(-lixo) %>%
  filter(lado3 != "NA") %>%
  mutate(mod = c(rep("intercept", 2), rep("slope", 2))) %>% 
  dplyr::select(-lado2)
names(reg1) = c("fungicide", "mean", "ci.lb", "ci.ub", "mod") 

mean = reg1 %>%
  group_by(fungicide) %>%
  dplyr::select(1:2,5) %>%
  spread(mod, mean) 
names(mean) = c("fungicide", "intercept_mean", "slope_mean")

upper = reg1 %>%
  group_by(fungicide) %>%
  dplyr::select(1,3,5) %>%
  spread(mod, ci.lb)
names(upper) = c("fungicide", "intercept_upper", "slope_upper")

lower = reg1 %>%
  group_by(fungicide) %>%
  dplyr::select(1,4:5) %>%
  spread(mod, ci.ub)
names(lower) = c("fungicide", "intercept_lower", "slope_lower")

data_model = left_join(mean, lower, by= c("fungicide")) %>% 
  left_join(upper, by = c("fungicide"))


```

```{r}
sbr_effic <- ma_sev %>%
  mutate(efficacy = (1-(mean_sev/sev_check))) %>% 
  mutate(efficacy1 = efficacy*100) %>% 
  filter(ai!= "AACHECK") %>% 
  filter(!efficacy1 <0)
  

year = seq(0,7, by = 0.1) 
fungicide = NULL
year_col = NULL
for(i in 1:length(data_model$fungicide)){
data_cache = sbr_effic %>% 
    filter(ai == data_model$fungicide[i]) 
years = unique(data_cache$year)-2017
year = sort(years)
year = seq(first(year), last(year), by = 0.1)   
  year_col = c(year_col,year) 
  fungicide = c(fungicide, rep(data_model$fungicide[i], length(year)))
}
 

predicted = data.frame(year_col, fungicide) %>%
  mutate(year = year_col) %>%
  right_join(data_model, by = "fungicide") %>%
  mutate(mean_efficacy = (1-exp(intercept_mean + slope_mean*year))*100,
         CIL = (1-exp(intercept_lower + slope_lower*year))*100,
         CIU = (1-exp(intercept_upper + slope_upper*year))*100,
         year = year+2017) %>% 
  mutate(brand_name = fungicide) %>% 
  filter(year <2023.2) %>% 
  dplyr::select(-fungicide)
predicted
```

#### Plot

```{r}

colnames(sbr_effic)[colnames(sbr_effic) == "ai"] <- "brand_name"

plot_sev = predicted %>% 
  mutate(brand_name = factor(brand_name, 
  levels = c("BIX + PROT + TRIFL","FLUX + PYRA"))) %>%
  ggplot()+
  geom_jitter(data = sbr_effic, aes(year, efficacy1, size = vi_sev),  alpha= 0.13, width = .2)+
  geom_line(data = predicted, aes(year, mean_efficacy), size = 1.7, color = "black")+
  geom_line(data = predicted, aes(year, CIL), linetype="dashed", size = 1, alpha = 1)+
  geom_line(data = predicted, aes(year, CIU), linetype="dashed", size = 1, alpha = 1)+
  theme_minimal_hgrid(font_size = 10)+
  scale_size_continuous(range = c(3,10), breaks = c(1,10,100))+

  guides(color = guide_legend(override.aes = list(size=2.5)))+
  theme(legend.position = "none",
        legend.justification = "top",
        legend.direction = "horizontal",
        legend.key.height = unit(1, "cm"),
        legend.title = element_text(size = 12, face = "bold"),
        legend.text = element_text(size = 12),
        panel.grid = element_blank(),
        axis.text.x = element_text(size = 10),
        axis.text.y = element_text(size = 10),
        axis.title.x = element_text(size=14, face = "bold"),
        axis.title.y = element_text(size=14, face = "bold"),
        strip.text = element_text(size = 12, 
                                  color = "black", face = "bold"),
        strip.background = element_rect(colour="white", fill="white"),
        panel.border = element_rect(color = "gray60", size=1))+
  scale_x_continuous(breaks=c(2017, 2018, 2019, 2020, 2021,2022,2023), limits=c(2017,2023))+
   scale_y_continuous(breaks=c(0, 10, 20, 30,40,50,60,70,80,90,100), limits=c(0,100))+
  labs(y = "Efficacy (%)", x = "Crop Season")+
  facet_wrap(~factor(brand_name), ncol = 2)+
  coord_cartesian(ylim=c(0,100))+
  labs(y = "Efficacy (%)", x = "", size = "Sampling Variance", color = "Region")
plot_sev
ggsave("fig/decline_efficacy.png", width = 8, height = 6, dpi = 600, bg = "white")
```

## Yield

```{r}
ma_yld <- ma_data %>% 
  filter(mean_yld != "NA")

hist(ma_yld$mean_yld)

```

```{r}
# Sampling variance for yield
ma_yld$vi_yld <- with(ma_yld, v_yld/4)

```

## Model fitting

### Overall

```{r}
mv_yld <- rma.mv(mean_yld, vi_yld,
  mods = ~ai,
  random = list(~ai | study),
  struct = "UN",
  method = "ML",
  control = list(optimizer = "nlm"),
  data = ma_yld)

summary(mv_yld)
```

##### Estimated

```{r}
yield_res<- data.frame(cbind(mv_yld$b, 
                             mv_yld$ci.lb,
                             mv_yld$ci.ub)) %>% 
  mutate(fungicide = c("check", "BIX + PROT + TRIFL","FLUX + PYRA")) %>% 
  filter(fungicide != "check")


names (yield_res) = c("yld", "yld_lower", "yld_upper", "fungicide")
  
yield_res
```

```{r}
mv_yld_means <- emmprep(mv_yld)
library(emmeans)

mv_yld_emmeans <- emmeans(mv_yld_means, ~ ai)
pwpm(mv_yld_emmeans)
```

### Year

```{r}
mv_yld_year <- rma.mv(mean_yld, vi_yld,
  mods = ~ai * as.numeric(year),
  random = list(~ai | study),
  struct = "UN",
  method = "ML",
  control = list(optimizer = "nlm"),
  data = ma_yld %>% mutate(year= year - 2017))

mv_yld_year
anova(mv_yld,mv_yld_year)
```

#### Declining

```{r}
mv_yld_year
```

##### Estimated

```{r}
reg1_yld = data.frame(mv_yld_year$beta, mv_yld_year$ci.lb, mv_yld_year$ci.ub) %>%
  rownames_to_column("trat") %>%
  tidyr::separate(trat, into = c("lado1", "lado2"), sep = ":") %>%
  separate(lado1, into = c("lixo", "lado3"),sep = "ai") %>%
  dplyr::select(-lixo) %>%
  filter(lado3 != "NA") %>%
  mutate(mod = c(rep("intercept", 2), rep("slope", 2))) %>% 
  dplyr::select(-lado2)
names(reg1_yld) = c("fungicide", "mean", "ci.lb", "ci.ub", "mod") 

mean_yld = reg1_yld %>%
  group_by(fungicide) %>%
  dplyr::select(1:2,5) %>%
  spread(mod, mean) 
names(mean_yld) = c("fungicide", "intercept_mean", "slope_mean")

upper_yld = reg1_yld %>%
  group_by(fungicide) %>%
  dplyr::select(1,3,5) %>%
  spread(mod, ci.lb)
names(upper_yld) = c("fungicide", "intercept_upper", "slope_upper")

lower_yld = reg1_yld %>%
  group_by(fungicide) %>%
  dplyr::select(1,4:5) %>%
  spread(mod, ci.ub)
names(lower_yld) = c("fungicide", "intercept_lower", "slope_lower")

data_model_yld = left_join(mean_yld, lower_yld, by= c("fungicide")) %>% 
  left_join(upper_yld, by = c("fungicide"))
```

```{r}
yld_gain <- ma_yld %>%
  mutate(gain = mean_yld - yld_check) %>% 
  filter(ai!= "AACHECK") %>% 
  filter(!gain <0)


year = seq(0,7, by = 0.1) 
fungicide = NULL
year_col = NULL
for(i in 1:length(data_model_yld$fungicide)){
data_cache = yld_gain %>% 
    filter(ai == data_model_yld$fungicide[i]) 
years = unique(data_cache$year)-2017
year = sort(years)
year = seq(first(year), last(year), by = 0.1)   
  year_col = c(year_col,year) 
  fungicide = c(fungicide, rep(data_model_yld$fungicide[i], length(year)))
}
 

predicted_yld = data.frame(year_col, fungicide) %>%
  mutate(year = year_col) %>%
  right_join(data_model_yld, by = "fungicide") %>%
  mutate(mean_gain = intercept_mean + slope_mean*year,
         CIL = intercept_lower + slope_lower*year,
         CIU = intercept_upper + slope_upper*year,
         year = year+2017) %>% 
  mutate(ai = fungicide) %>% 
  filter(year <2023.2) %>% 
  dplyr::select(-fungicide)
predicted_yld
```

#### Plot

```{r}
plot_yld = predicted_yld %>% 
 # mutate(brand_name = factor(ai, levels = c("BIX + PROT + TRIFL","FLUX + PYRA"))) %>%
  ggplot()+
  geom_jitter(data = yld_gain, aes(year, gain, size = vi_yld), alpha= 0.13, width = 0.2)+
  geom_line(data = predicted_yld, aes(year, mean_gain), size = 1.7, color = "black")+
  geom_line(data = predicted_yld, aes(year, CIL), linetype="dashed", size = 1, alpha = 1)+
  geom_line(data = predicted_yld, aes(year, CIU), linetype="dashed", size =1, alpha = 1)+
  theme_minimal_hgrid(font_size = 10)+
  guides(color = guide_legend(override.aes = list(size=2.5)))+
  theme(legend.position = "none",
        legend.justification = "top",
        legend.direction = "horizontal",
        legend.key.height = unit(1, "cm"),
        legend.title = element_text(size = 12, face = "bold"),
        legend.text = element_text(size = 12),
        panel.grid = element_blank(),
        axis.text.x = element_text(size = 10),
        axis.text.y = element_text(size = 10),
        axis.title.x = element_text(size=14, face = "bold"),
        axis.title.y = element_text(size=14, face = "bold"),
        strip.text = element_text(size = 12, color = "black"),
        #strip.background = element_rect(colour="white", fill="white"),
        panel.border = element_rect(color = "gray60", size=1),
        strip.background = element_blank(),
        strip.text.x = element_blank())+
   scale_y_continuous(breaks=c(0, 250, 500, 750, 1000, 1250,1500,1750,2000,2250,2500), limits=c(0,2500))+
  scale_x_continuous(breaks=c(2017, 2018, 2019, 2020, 2021, 2022,2023), limits=c(2017,2023))+
  labs(y = "Yield response (kg/ha)", x = "Harvest Season",size = "Sampling Variance")+
  facet_wrap(~factor(ai), ncol = 2)

plot_yld
```

```{r}
plot_grid(plot_sev,plot_yld, ncol = 1, labels = c("AUTO"))
ggsave("fig/decline_efficacy_sev_yld.png", width = 8, height = 10, dpi = 600, bg = "white")

```




